teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1                                    # Left thumbstick vertical
      y: 0                                    # Left thumbstick horizontal
    scale_linear:
      x: 0.5
      y: 0.5
    scale_linear_turbo:
      x: 1.0
      y: 1.0

    axis_angular:
      yaw: 2                                  # Right thumbstick horizontal
    scale_angular:
      yaw: 0.3

    cmd_vel_topic: "cmd_vel"                  # Default: "cmd_vel"
    joy_topic: "joy"                          # Default: "joy"
    linear_acceleration_limit: 0.2
    linear_deceleration_limit: 0.2
    angular_acceleration_limit: 0.15
    angular_deceleration_limit: 0.15

    side_conveyor_button: 1                   # B button
    back_conveyor_button: 0                   # A button

    error_reset_button: 2                     # DISABLED
    enable_button: 4                          # RT shoulder trigger AXIS NOT BUTTON
    enable_turbo_button: 6                    # LB shoulder button
