teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1  #left thumbstick vertical
      y: 0  #left thumbstick horizontal
    scale_linear:
      x: 1.0
      y: 1.0
    scale_linear_turbo:
      x: 1.5
      y: 1.5

    axis_angular:
      yaw: 2  #right thumbstick horizontal
    scale_angular:
      yaw: 0.4

    enable_button: 7  # RB shoulder button
    enable_turbo_button: 6  # LB shoulder button

    linear_acceleration_limit: 0.2
    linear_deceleration_limit: 0.1

    angular_acceleration_limit: 0.08
    angular_deceleration_limit: 0.08
