teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1 #left thumbstick vertical
      y: 0 #left thumbstick horizontal
    scale_linear:
      x: 0.4
      y: 0.4
    axis_angular:
      yaw: 3 #right thumbstick horizontal
    scale_angular:
      yaw: 0.5
    enable_button: 5
    enable_turbo_button: 2
