teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1                                    # Left thumbstick vertical
      y: 0                                    # Left thumbstick horizontal
    scale_linear:
      x: 0.5
      y: 0.5
    scale_linear_turbo:
      x: 1.0
      y: 1.0

    axis_angular:
      yaw: 2                                  # Right thumbstick horizontal
    scale_angular:
      yaw: 1.0 

    axis_joint:
      x: 1                                    # Left thumbstick vertical
    scale_joint: 
      x: 0.8
    scale_joint_turbo:
      x: 1.0

    enable_button: 7                          # RB shoulder button
    enable_turbo_button: 6                    # LB shoulder button
    enable_mode_button: 12                    # XBOX logo button
    enable_gripper_button: 0                  # A button
    prev_joint_button: 3                      # X button
    next_joint_button: 1                      # B button

    linear_acceleration_limit: 0.12
    linear_deceleration_limit: 0.12
    angular_acceleration_limit: 0.055
    angular_deceleration_limit: 0.055
    joint_velocity_limit: 0.4

    # joints: 
    #   # NAMES                       MIN, MAX
    #   "base_rotation_joint"   : [ -3.14, 3.14  ]
    #   "camera_rotation_joint" : [ -3.14, 3.14  ]
    #   "elbow_rotation_joint"  : [ -2.61, 2.61  ] 
    #   "h_gantry_joint"        : [   0.0, 0.75  ]
    #   "rotation1_joint"       : [ -1.57, 1.57  ]
    #   "rotation2_joint"       : [ -3.14, 3.14  ]
    #   "v_gantry_joint"        : [   0.0, 1.061 ]
    #   "wrist_rotation_joint"  : [ -3.14, 3.14  ]
    joint_names: [
      "h_gantry_joint"        ,     
      "elbow_rotation_joint"  , 
      "wrist_rotation_joint"  ,
      "front_swerve_joint"    ,
      "base_rotation_joint"   ,
      "rotation2_joint"       ,
      "front_hub_joint"       ,      
      "v_gantry_joint"        ,       
      "camera_rotation_joint" ,
      "rear_swerve_joint"     ,
      "rotation1_joint"       ,
      "rear_hub_joint"        ,     
    ]

    joint_limits_min: [
      0.0,
      -2.61,
      -3.14,
      0.0 , #-3.14,
      -3.14,
      -3.14,
      0.0,
      0.0,
      -3.14,
      0.0 , #-3.14,
      -1.57,
      0.0
    ]

    joint_limits_max: [
      0.75,
      2.61,
      3.14,
      0.0 , #3.14,
      3.14,
      3.14,
      0.0,
      1.061,
      3.14,
      0.0 , #3.14,
      1.57,
      0.0
    ]