teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1                                    # Left thumbstick vertical
      y: 0                                    # Left thumbstick horizontal
    scale_linear:
      x: 0.15
      y: 0.15
    scale_linear_turbo:
      x: 0.3
      y: 0.3

    axis_angular:
      yaw: 2                                  # Right thumbstick horizontal
    scale_angular:
      yaw: 0.05

    cmd_vel_topic: "cmd_vel"                  # Default: "cmd_vel"
    joy_topic: "joy"                          # Default: "joy"
    linear_acceleration_limit: 0.2
    linear_deceleration_limit: 0.2
    angular_acceleration_limit: 0.15
    angular_deceleration_limit: 0.15

    enable_button: 4                          # RT shoulder trigger AXIS NOT BUTTON
    enable_turbo_button: 6                    # LB shoulder button
    
    conveyor_right_button: 1                  # B button
    conveyor_left_button: 3                   # X button
    conveyor_front_button: 4                  # Y button
    conveyor_back_button: 0                   # A button
    conveyor_all_button: 6                    # D-pad left
    conveyor_dir_button: 7                    # D-pad front and back

    conveyor_right_vel: 0.27
    conveyor_left_vel: -0.27
    conveyor_back_vel: 1.18
    conveyor_front_vel: 0.42